function [events] = Deuteron_GetDigInEvents(EventRecord)
% INPUT:
%       EventRecords struct generated by Deuteron_EventFileReader.
% OUTPUT:
%       cell array containing time points (as minutes from midnight), in the
%       first column, the sample number, in the the second column, and the pins that
%       were turned on (only 'rising' edges) in the third column.
% 
%       if no events were sent to the system, the cell array returns the a
%       2x2 matrix with the start and end of the recording, as minutes from 
%       midnight, in the first column, and the sample numbers of these timestamps 
%       in the second column.
%
% VERSION HISTORY:
% Author:         Aylin Apostel
% Version:        1.2.0
% Last Change:    01.02.2023
%
% 12.11.2021, Aylin: first draft 
% 31.03.2022, Sara: Added conversion to sample number and option to get 
%                   event output when no transitions were logged in the Deuteron system
% 19.04.2022, Sara: Added the interaction between Matlab and Deuteron's .NET
%                   app for event reading, in order to automate this process.
%                   No further need to convert the event file "EVENTLOG.NLE" into a .CSV. 
%                   Currently, this code only works for recordings in flat format
% 01/02/2023, Jesus: Separated Event collection via dll from DigIn events
%                   extraction.

%% Take timestamp of first file opening
fileStart = contains({EventRecord.EventType}.', 'File started');
idx = find(fileStart,1,"first");
firstFileStartTime = EventRecord(idx).TimeMsFromMidnight;

fileStart = contains({EventRecord.Details}.', 'Started recording');
idx = find(fileStart,1,"first");
RecordingStartTime = EventRecord(idx).TimeMsFromMidnight;

% TODO Continue here when I get a recording with EVENTS
% Get all lines with 'Digital in':
digIn     = contains(EventRecord(:,5),'Digital in');

if ~any(digIn) %no event codes were sent to the logger 
    events = cell(2,2); %first column: ms from midnight; second column: number of sample 
    events{1,1} = firstFileStartTime; %opening of 1st file (ms from midnight)
    events{2,1} = cell2mat(EventRecord(end,3));%end of recording session(ms from midnight)
    if events{2,1} ==0 %a restart of the logger (internal workings of Deuteron)
        events{2,1} = cell2mat(EventRecord(end-1,3));
    end 
    events{1,2} = 1; %sample nr at file opening 
    events{2,2} = (events{2,1} - firstFileStartTime(1,1))*samplesMs; %last sample recorded 
    
else % events were sent 
    digitalIn = EventRecord(any(digIn,2),:);
    events = cell(size(digitalIn,1),3); %###
    events(:,1) = digitalIn(:,3); % all timepoints
    
    % Which pin changed?
    for i = 1 : size(digitalIn,1)
        dat = digitalIn(i,:);
        if contains(dat{1,6},'1')
            pin = 1;
        elseif contains(dat{1,6},'2')
            pin = 2;
        elseif contains(dat{1,6},'3')
            pin = 3;
        elseif contains(dat{1,6},'4')
            pin = 4;
        end
        events(i,3) = {pin};
    end
    
    for g = 1:length(events)
        events(g,2) = num2cell((cell2mat(events(g,1))-firstFileStartTime(1,1))*samplesMs); %sample number of the 
    end                             %sample that was being recorded when the event occured 
end

end