function [events, trialdef, EventRecord] = Deuteron_EventProcess(opt)
% Function meant to put together all possible ways to extract events from
% Deuteron systems (using exe, using dll or using text format)
%
% Jesus 11.06.2024

%% Defaults.
% if ~isfield(opt,'useexe'),          opt.useexe              = false;                end
% if ~isfield(opt,'useRes'),          opt.useRes              = false;                end
if ~isfield(opt,'eventdef'),        opt.eventdef            = eventDefinitions();   end
if ~isfield(opt,'trEvents'),        opt.trEvents            = [];                   end

%% Prep. Make sure we create empty outputs
events      = []; % If remains empty, data shall be treated as continuous.
trialdef    = [];
EventRecord = [];

%% Check for alredy collected events
if isfile(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')))
    disp('EventRecord found. Loading.')
    load(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')), 'EventRecord');

    if isfile(fullfile(opt.trialSorted, strcat('trialdef.mat')))
        disp('Trial definition file found. Assuming events have been collected. Loading both.')
        load(fullfile(opt.trialSorted, strcat('events.mat')), 'events');
        load(fullfile(opt.trialSorted, strcat('trialdef.mat')), 'trialdef');

        % Done here
        return
    end
end

%% Retrieve Events and generate needed variables
if opt.RetrieveEvents
    % So far, appears like we can only save Events in SD card of 32ch headstages with
    % SSNN 13 and 14, requiring a FLAT format.
    % For the rest (32ch SSNN 11 and 12 or 64ch SSNN 3 and 2), the events will be 
    % retrieved from the txt lof file created by deuteron, which is timestamped as 
    % the logger clock.

%    DEPR if opt.useexe % When extracting events from SD using EXE. Very easy to use vs dll
%         
%         % Proceed to extract all events captured by Deuteron acquisition system,
%         % stored along with the data and synchronized with it (proper timestamped).
%         disp('Retrieving events from Deuteron Event files using EXE.')
%         [EventRecord, opt] = Deuteron_ExtractEvents(opt); % NEEDS clean up for dlls
% 
%     elseif opt.useRes % Temporary solution, working on Juan's social paradigms
%         
%         % In this case, events are recovered from a matlab variable created during the 
%         % the experimental session, commonly '*_par.mat'. Matlab captures the eventcodes
%         % generated by OTBR as they come out of the paradigm run, they are NOT
%         % the events captured by the ephys acquisition system. 
%         disp('Creating trial definitions based on res.m file.')
%         EventRecord = trialdefFromPar(opt);
% 
%         % Then, based on the trial definitions (defaulted or given) create
%         % an 'events' struct fitting the NGL convention
%         [events, trialdef, opt.eventdef] = trialdefGen(EventRecord, opt);
% 
%     else % DEFAULT when using Deuteron. Uses txt file generated at logging PC 
%         
        % First create the EventRecord 'as it would come out of Deuteron'
    
    try EventRecord = Deuteron_ExtractLogEvents(opt);
    catch % In case logevent.txt does not exist, BUT res.mat file does
        if isfile(ls('*res.mat'))
            disp('Creating trial definitions based on res.m file.')
            EventRecord = trialdefFromPar(opt);
        end
    end

    % Then, based on the trial definitions (defaulted or given) create
    % an 'events' struct fitting the NGL convention
    disp('Creating trial definitions based on extracted EventRecord and Eventcodes descriptions.')
    [events, trialdef, opt.eventdef] = trialdefGen(EventRecord, opt);
%   DEPR  end

    %% Create the conditions variable for trial indexing
    % Initialize all fields with zeros
    zerovec = zeros(length(events.itiOn.code),1);
    condition = struct( 'correct', zerovec, 'incorrect', zerovec, 'omission', zerovec, ...
                        'response', zerovec, 'aborted', zerovec, 'stimulus', zerovec);
    
    % Trial by trial, classify them. Using 'itiOn' bc it should be the minimal
    % choice of alignment, and events are the same for any alignment.
    for i=1:length(events.itiOn.code)
        trialvect = events.itiOn.code{i,1};
        if sum(ismember(trialvect, [opt.eventdef.bhv opt.eventdef.rwd]))==2
            condition.response(i) = 1;
            condition.correct(i) = 1;
        end
        if sum(ismember(trialvect, [opt.eventdef.bhv opt.eventdef.pun]))==2
            condition.response(i) = 1;
            condition.incorrect(i) = 1;
        end
        if any(ismember(trialvect, [opt.eventdef.oms1 opt.eventdef.oms2]))
            condition.omission(i) = 1;
        end
        % FOR MORE add as (with corresponding logical index): 
        % if ismember(trialvect, [opt.eventdef.xxx opt.eventdef.yyy])
        %     condition.xxxyyy(i) = 1;
        % end
        % if ismember(trialvect, [opt.eventdef.xxx opt.eventdef.yyy])
        %     condition.xxxyyy(i) = 1;
        % end
    end

else
    disp('Events not requested. Skipped.')
end

%% Save this session events, trialdef and conditions variables.
save(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')), 'EventRecord', '-v7.3');
save(fullfile(opt.trialSorted, strcat('trialdef.mat')), 'trialdef', '-v7.3');
save(fullfile(opt.analysis, strcat('events.mat')), 'events', '-v7.3');
save(fullfile(opt.analysis, strcat('condition.mat')), 'condition', '-v7.3');

end