function [events, trialdef, EventRecord] = Deuteron_EventProcess(opt)
% Function meant to put together all possible ways to extract events from
% Deuteron systems (using exe, using dll or using text format)
%
% Jesus 05.03.2024

% As far as they exist as options, we need them to exist
if ~isfield(opt,'useexe'),          opt.useexe              = false;        end
if ~isfield(opt,'usepar'),          opt.usepar              = false;        end

% Make sure we create empty outputs
events      = []; % If remains empty, data shall be treated as continuous.
trialdef    = [];
EventRecord = [];

% Go for it
if opt.RetrieveEvents 
    % So far, appears like we can only save Events in SD card of 32ch headstages with
    % SSNN 13 and 14, requiring a FLAT format.
    % For the rest (32ch SSNN 11 and 12 or 64ch SSNN 3 and 2), the events will be 
    % retrieved from the txt lof file created by deuteron, which is timestamped as 
    % the logger clock.

    if opt.useexe % When extracting events from SD using EXE. Very easy to use vs dll
        % Proceed to extract all events captured by Deuteron acquisition system,
        % stored along with the data and synchronized with it (proper timestamped).
        disp('Retrieving events from Deuteron Event files using EXE.')
        [EventRecord, opt] = Deuteron_ExtractEvents(opt); % NEEDS clean up for dlls

    elseif opt.usepar % Temporary solution, working on Juan's social paradigms
        % In this case, events are recovered from a matlab variable created during the 
        % the experimental session, commonly '*_par.mat'. Matlab captures the eventcodes
        % generated by OTBR as they come out of the paradigm run, they are NOT
        % the events captured by the ephys acquisition system. 
        disp('Creating trial definitions based on _par file.')
        [events, opt.eventdef] = trialdefFromPar(opt);

    else % IN PRINCIPLE DEFAULT when using Deuteron. Use txt file generated from local PC logging
        % First create the EventRecord 'as it would come out of Deuteron'
        EventRecord = Deuteron_ExtractLogEvents(opt);
    
        % Then, based on the trial definitions (defaulted or given) create
        % an 'events' struct fitting the NGL convention
        disp('Creating trial definitions based on extracted EventRecord and Eventcodes descriptions.')
        [events, trialdef, opt.eventdef] = trialdefGen(EventRecord, opt);
    end

else
    disp('Events not requested. Skipped.')
end

% Save this session events and trialdef.
save(fullfile(opt.FolderProcDataMat, strcat('events.mat')), 'events', '-v7.3')
save(fullfile(opt.FolderProcDataMat, strcat('trialdef.mat')), 'trialdef', '-v7.3')
save(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')), 'EventRecord', '-v7.3')

end