function [events, trialdef, EventRecord] = Deuteron_EventProcess(opt)
% Function meant to put together all possible ways to extract events from
% Deuteron systems (using exe, using dll or using text format)
%
% Jesus 05.03.2024

% As far as they exist as options, we need them to exist
if ~isfield(opt,'useexe'),          opt.useexe              = false;        end
if ~isfield(opt,'useRes'),          opt.useRes              = false;        end
if ~isfield(opt,'eventdef')
    opt.eventdef = struct;
        % Descriptions            = Decimal  % Comments
        opt.eventdef.preIni       = 8;       % FIXED! Last resource to delimit end-trial. Also, start/end-session.
        opt.eventdef.itiOn        = 0;       % FIXED! Delimits start-trial.
        opt.eventdef.stimOn1      = 1;       % 
        opt.eventdef.stimOn2      = 2;       %
        opt.eventdef.bhv          = 3;       %
        opt.eventdef.oms1         = 5;       %
        opt.eventdef.oms2         = 6;       %
        opt.eventdef.rwd          = 7;       %
        opt.eventdef.pun          = 11;      %
        opt.eventdef.end1         = 4 ;      % omsX-end.
        opt.eventdef.end2         = 10;      % pun-end.
        opt.eventdef.end3         = 15;      % rwd-end.
        opt.eventdef.na1          = 12;      % Transition sequence
        opt.eventdef.na2          = 14;      % Transition sequence
        opt.eventdef.tr1          = 9;       % Treatment1?
        opt.eventdef.na3          = 13;      % 
  
        % Set event to align trial times (event with t=0)
        opt.eventdef.t0           = opt.eventdef.itiOn;
end

%% Asess existence of trialdefinitions
if ~isfile(fullfile(opt.FolderProcDataMat, strcat('trialdef.mat')))

    % Make sure we create empty outputs
    events      = []; % If remains empty, data shall be treated as continuous.
    trialdef    = [];
    EventRecord = [];
    
    % Go for it
    if opt.RetrieveEvents 
        % So far, appears like we can only save Events in SD card of 32ch headstages with
        % SSNN 13 and 14, requiring a FLAT format.
        % For the rest (32ch SSNN 11 and 12 or 64ch SSNN 3 and 2), the events will be 
        % retrieved from the txt lof file created by deuteron, which is timestamped as 
        % the logger clock.
    
        if opt.useexe % When extracting events from SD using EXE. Very easy to use vs dll
            % Proceed to extract all events captured by Deuteron acquisition system,
            % stored along with the data and synchronized with it (proper timestamped).
            disp('Retrieving events from Deuteron Event files using EXE.')
            [EventRecord, opt] = Deuteron_ExtractEvents(opt); % NEEDS clean up for dlls
    
        elseif opt.useRes % Temporary solution, working on Juan's social paradigms
            % In this case, events are recovered from a matlab variable created during the 
            % the experimental session, commonly '*_par.mat'. Matlab captures the eventcodes
            % generated by OTBR as they come out of the paradigm run, they are NOT
            % the events captured by the ephys acquisition system. 
            disp('Creating trial definitions based on res.m file.')
            EventRecord = trialdefFromPar(opt);
    
            % Then, based on the trial definitions (defaulted or given) create
            % an 'events' struct fitting the NGL convention
            [events, trialdef, opt.eventdef] = trialdefGen(EventRecord, opt);

        else % IN PRINCIPLE DEFAULT when using Deuteron. Use txt file generated from local PC logging
            % First create the EventRecord 'as it would come out of Deuteron'
            try EventRecord = Deuteron_ExtractLogEvents(opt);
            catch % In case logevent.txt does not exist, BUT res.mat file does
                if isfile(ls('*res.mat'))
                    disp('Creating trial definitions based on res.m file.')
                    EventRecord = trialdefFromPar(opt);
                end
            end

            % Then, based on the trial definitions (defaulted or given) create
            % an 'events' struct fitting the NGL convention
            disp('Creating trial definitions based on extracted EventRecord and Eventcodes descriptions.')
            [events, trialdef, opt.eventdef] = trialdefGen(EventRecord, opt);
        end
    
    else
        disp('Events not requested. Skipped.')
    end
    
    % Save this session events and trialdef.
    save(fullfile(opt.FolderProcDataMat, strcat('events.mat')), 'events', '-v7.3')
    save(fullfile(opt.FolderProcDataMat, strcat('trialdef.mat')), 'trialdef', '-v7.3')
    save(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')), 'EventRecord', '-v7.3')
else
    disp('Event codes and Trial definitions already existing. Skipping.')
    load(fullfile(opt.FolderProcDataMat, strcat('events.mat'))); % If remains empty, data shall be treated as continuous.
    load(fullfile(opt.FolderProcDataMat, strcat('trialdef.mat')));
    load(fullfile(opt.FolderProcDataMat, strcat('EventRecord.mat')));
end

end