function bhvResults = retrieve_bhvResults(input)
% The data generated by the matlab session in this experiment (a 'res.mat'
% file, or 'res' variable extracted from a similar .mat file) must be stored
% in the behavioral folder of the data, for each subject and session, as 
% 'bhvResults.mat'.

bhvResults = [];
cd(fullfile(input.bhvfolder, input.subjects.name, input.sessions.list{input.run(2)}))

if isfile("bhvResults.mat")
    tmp = load("bhvResults.mat");
    if isfield(tmp,'bhvResults')
        bhvResults = tmp.bhvResults;
        if isfield(bhvResults,'summ')
            disp('Behavioral results were summarized before. Skipping.');
            return
        else
            bhvResults = proceed(bhvResults);
        end
    else
        if isfield(tmp,'res')
            tmp = tmp.res;
            if ~isfield(tmp,'summ')
                bhvResults = tmp;
                bhvResults = proceed(bhvResults);
            end
        end
    end
else
    disp('Behavioral results from ''res.mat'' file not possible, because the file was not found');
    return
end

end

function bhvResults = proceed(bhvResults)
    bhvResults.summ.n.all   = bhvResults.INI_trls;
    bhvResults.summ.n.init  = sum(bhvResults.INI_res==1);
    bhvResults.summ.n.iniacq = bhvResults.A_trls;
    bhvResults.summ.n.allacq = bhvResults.A_end_trls;
    bhvResults.summ.n.iniext = bhvResults.B_trls;
    bhvResults.summ.n.allext = bhvResults.B_end_trls - bhvResults.A_end_trls;
    bhvResults.summ.n.iniT  = 25*6;
    bhvResults.summ.n.allT  = bhvResults.summ.n.all - bhvResults.summ.n.allacq - bhvResults.summ.n.allext;
    
    bhvResults.summ.start.acq = [bhvResults.A_begin_trls; 0];
    bhvResults.summ.start.ext = [bhvResults.B_begin_trls; bhvResults.B_begin_time*60];
    bhvResults.summ.start.T   = [bhvResults.T_begin_trls{:}; bhvResults.T_begin_time{:}];
        bhvResults.summ.start.T(2,:)= bhvResults.summ.start.T(2,:)*60;
    bhvResults.summ.start.all = [bhvResults.tstart - bhvResults.tstart(1);
                                [diff(bhvResults.tstart) 0]];
    
    bhvResults.summ.end.acq = [bhvResults.A_end_trls; bhvResults.A_end_time*60];
    bhvResults.summ.end.ext = [bhvResults.B_end_trls; bhvResults.B_end_time*60];
    bhvResults.summ.end.T   = [bhvResults.T_end_trls{:}; bhvResults.T_end_time{:}];
        bhvResults.summ.end.T(2,:)= bhvResults.summ.end.T(2,:)*60;
    bhvResults.summ.end.all = sum(bhvResults.summ.start.all,1);
        bhvResults.summ.end.all(end) = bhvResults.summ.end.T(2,end);
    
    save("bhvResults.mat","bhvResults")
    disp('Behavioral results from ''res.mat'' recovered, summarized, and saved.');
end