function bombcellReason(varargin)
% Generates an interactive (sortable) table of the bombcell quality metrics
% to assist Phy curation. Factors used by Bombcell to classify the unit
% types are highlighted and colour-coded.
%
% This function can be run in three ways:
% 1) Without input arguments, assume the current directory is the
% generated bombcell folder containing 'templates._bc_qMetrics_all.csv'
% 2) bombcellReason(opt) uses the NGL_ephysPipeline struct 'opt' for the
% location of the generated bombcell folder
% 3) bombcellReason("Directory") takes a string or char array of the file
% directory of the generated bombcell folder
%
% OUTPUT:
% Generates a uifigure of the interactive table and saves the table data
% and formatting (colour coding) to bombcellReasonOutput.xlsx specified
% by bombcellFolder.
% uif = uifigure
% uit = uitable
% uit.Data(:,1)     % Phy Cluster ID
% uit.Data(:,2)     % Kilosort label (unit type)
% uit.Data(:,3)     % Bombcell unit type
% uit.Data(:,4:end) % Bombcell quality metrics. Detailed explanations of quality metrics can be found here: https://github.com/Julie-Fabre/bombcell/wiki/Detailed-overview-of-quality-metrics
% qMetric           % Generated metrics from the raw waveforms
% param             % User (or default) settings for parameter thresholds for unit type decision-making (classification)
%
% Version 16/10/2025 (Winston)

%% Resolve input arguments
if isempty(varargin)
    bombcellFolder = pwd;                                        % Without input arguments, must be run in the bombcell folder containing 'templates._bc_qMetrics_all.csv' of the current recording
elseif nargin == 1
    if isstruct(varargin{1}) && isfield(varargin{1},'KSfolder')
        opt = varargin{1};
        bombcellFolder = fullfile(opt.KSfolder,'bombcell');      % Expecting 'opt' struct from NGL pipeline
    elseif ischar(varargin{1}) | isstring(varargin{1})
        bombcellFolder = varargin{1};                               % Expecting char array or string of bombcell directory containing 'templates._bc_qMetrics_all.csv' of the current recording
    end
end
bombcellFolder = char(bombcellFolder);                           % Force char for split() output consistency
configFolder = split(bombcellFolder,'\');                        % Assume standard NGL folder structure generated by NGL00_Prep to locate bombcellConfig.m in analysisCode.
configFolder = fullfile(configFolder{1:find(cellfun(@(x) strcmp(x,'data'),configFolder))-1},'analysisCode'); % Uses 'data' subfolder to determine directory of 'ProjectName\analysisCode'
%% Load quality metrics table and bombcellConfig (containing threshold settings)
qMetric = readtable(fullfile(bombcellFolder,'templates._bc_qMetrics_all.csv')); % Load quality metric table the same format as bombcell after saveQMetrics.m
if ~exist('opt')
    opt.FolderProcDataMat = split(bombcellFolder,'\');
    opt.FolderProcDataMat = fullfile(opt.FolderProcDataMat{1:end-2}); % bombcellConfig.m currently needs opt.FolderProcDataMat to run, derive from bombcellFolder
end
if exist('input') ~= 1 % because 'input' exists as base function (== 5)
    KSfolder = split(bombcellFolder,'\');
    KSfolder = fullfile(KSfolder{1:end-1}); % Parent folder of bombcell is (usually) kilosort4
    text = char(fread(fopen(fullfile(KSfolder,'params.py')))');
    input = struct([]); % need to override 'input' base function
    input(1).sessions.info.amplifier_sample_rate = str2num(erase(cell2mat(regexp(text,'sample_rate = \d*','match')),'sample_rate = ')); % Extract sampling rate value from params.py text
end
run(fullfile(configFolder,'bombcellConfig.m')); % Generates "param" variable that contains the calculated thresholds for quality metrics (for classification)
% Run bombcell param check and name unifier
addpath('C:\Code\ephys-data-pipeline\toolboxes\bombcell\matlab')
param = bc.qm.checkParameterFields(param);
[qMetric, param] = bc.qm.prettify_names(qMetric, param);
%% Markup qMetric table for reasons of cluster classification (Good, MUA, Non-somatic,etc.)
% Create logical index matching size of quality metric table?
% Follow bombcell classification order (Noise,MUA,Good,Non-somatic) to
% avoid errors in sequential logic, also good to group relevant params
% See getQualityUnitType.m in bombcell\matlab\+bc\+qm
noiseMetric = ["nPeaks","nTroughs","waveformDuration_peakTrough","waveformBaselineFlatness","scndPeakToTroughRatio","spatialDecaySlope"];
noiseIdx = ...
    [isnan(qMetric.nPeaks) | qMetric.nPeaks > param.maxNPeaks ...
    qMetric.nTroughs > param.maxNTroughs ...
    qMetric.waveformDuration_peakTrough < param.minWvDuration | qMetric.waveformDuration_peakTrough > param.maxWvDuration ...
    qMetric.waveformBaselineFlatness > param.maxWvBaselineFraction ...
    qMetric.scndPeakToTroughRatio > param.maxScndPeakToTroughRatio_noise];
if param.computeSpatialDecay == 1 && param.spDecayLinFit == 1
    idx = qMetric.spatialDecaySlope > param.minSpatialDecaySlope;
else
    idx = qMetric.spatialDecaySlope < param.minSpatialDecaySlopeExp | qMetric.spatialDecaySlope > param.maxSpatialDecaySlopeExp;
end
noiseIdx = cat(2,noiseIdx,idx);

muaMetric = ["percentageSpikesMissing_gaussian","nSpikes","fractionRPVs_estimatedTauR","presenceRatio"];
muaIdx = ...
    [qMetric.percentageSpikesMissing_gaussian > param.maxPercSpikesMissing ...
    qMetric.nSpikes < param.minNumSpikes ...
    qMetric.fractionRPVs_estimatedTauR > param.maxRPVviolations ...
    qMetric.presenceRatio < param.minPresenceRatio];
try
    if param.computeDistanceMetrics && ~isnan(param.isoDmin)
        idx = [qMetric.isolationDistance < param.isoDmin ...
            qMetric.Lratio > param.lratioMax];
    end
catch
    if param.computeDistanceMetrics && ~isnan(param.minIsoD) % Name not fixed in prettify?
        idx = [qMetric.isolationDistance < param.minIsoD ...
            qMetric.Lratio > param.lratioMax];
    end
    muaMetric = cat(2,muaMetric,["isolationDistance","Lratio"]);
    muaIdx = cat(2,muaIdx,idx);
end
if param.extractRaw
    idx = [qMetric.rawAmplitude < param.minAmplitude ...
        qMetric.signalToNoiseRatio < param.minSNR];
    muaMetric = cat(2,muaMetric,"rawAmplitude","signalToNoiseRatio");
    muaIdx = cat(2,muaIdx,idx);
end
if param.computeDrift
    idx = qMetric.maxDriftEstimate > param.maxDrift;
    muaMetric = cat(2,muaMetric,"maxDriftEstimate");
    muaIdx = cat(2,muaIdx,idx);
end

goodIdx = ~(any(noiseIdx,2) | any(muaIdx,2));

nonSomaMetric = ["troughToPeak2Ratio","mainPeak_before_width","mainTrough_width","peak1ToPeak2Ratio","mainPeakToTroughRatio"];
nonSomaIdx = ... % First 4 factors must all be True, or 5th factor must be true to be labelled non-soma
    [qMetric.troughToPeak2Ratio < param.minTroughToPeak2Ratio_nonSomatic ...
    qMetric.mainPeak_before_width < param.minWidthFirstPeak_nonSomatic ...
    qMetric.mainTrough_width < param.minWidthMainTrough_nonSomatic ...
    qMetric.peak1ToPeak2Ratio > param.maxPeak1ToPeak2Ratio_nonSomatic...
    qMetric.mainPeakToTroughRatio > param.maxMainPeakToTroughRatio_nonSomatic];

% Logical indexing for unit labels:
% any(noiseIdx,2)                                              % Noise label
% any(muaIdx,2)                                                % MUA label
% goodIdx                                                      % Good label
% goodIdx       & (all(nonSomaIdx(:,1:4),2) | nonSomaIdx(:,5)) % Non-Soma good label
% any(muaIdx,2) & (all(nonSomaIdx(:,1:4),2) | nonSomaIdx(:,5)) % Non-Soma mua label

% Determine unit type
unitType = strings(height(qMetric),1); % Could preallocate with strings(N,0) for isempty(), but trailing emptys are removed and vector length becomes inconsistent
unitType(any(noiseIdx,2))                                                   = "Noise";
unitType(any(muaIdx,2) & strcmp(unitType,""))                               = "MUA";
unitType(goodIdx)                                                           = "Good";
if param.splitGoodAndMua_NonSomatic
    unitType(goodIdx & (all(nonSomaIdx(:,1:4),2) | nonSomaIdx(:,5)))        = "Non-Soma Good";
    unitType(any(muaIdx,2) & (all(nonSomaIdx(:,1:4),2) | nonSomaIdx(:,5)))  = "Non-Soma MUA";
else
    unitType(all(nonSomaIdx(:,1:4),2) | nonSomaIdx(:,5))                    = "Non-Soma";
end

%% Create new table ordered by selection criteria
% Grouping associated params improves legibility
KSlabel = string(tdfread(fullfile(opt.FolderProcDataMat,'kilosort4','cluster_KSLabel.tsv')).KSLabel);
newTable = [qMetric(:,"phy_clusterID") table(KSlabel) table(unitType) qMetric(:,noiseMetric)  qMetric(:,muaMetric) qMetric(:,nonSomaMetric)];
uif = uifigure("WindowState", "maximized");
pause(0.1); drawnow;  % Allow uifigure to load to full size before positioning uitable
uit = uitable(uif,"ColumnWidth","1x","Data",newTable,"Position",[1 1 uif.Position(3) uif.Position(4)],"ColumnSortable",true);
% Colour scheme
if param.splitGoodAndMua_NonSomatic
    unitTypeNames = ["Noise", "MUA", "Good", "Non-Soma MUA", "Non-Soma Good"];
    cmap = parula(3); cmap = [cmap; cmap(2:3,:)*0.7]; % Non-Soma are darker but matching MUA/Good
else
    unitTypeNames = ["Noise", "MUA", "Good", "Non-Soma"];
    cmap = [parula(3); 0.5 0.5 0.5]; % Non-Soma is gray
end
cmap = rescale(cmap,0.3,1); % Increase brightness of colours for better contrast against black text
% Conditional highlighting indexes
UTcol = find(strcmp(newTable.Properties.VariableNames,'unitType'));
fullIdx = [zeros(height(uit.Data),UTcol) noiseIdx muaIdx nonSomaIdx]; % match uitable size
typeIdx = cumsum([UTcol+1 length(noiseMetric) length(muaMetric) length(nonSomaMetric)]); % Start-column index for each type (Noise, MUA, Non-Soma, end+1)

for i = 1:size(cmap,1) % Highlight by each unit type
    s = uistyle("BackgroundColor",cmap(i,:));
    idx = zeros(size(uit.Data)); % preallocate logical index for shading background
    idx(:,UTcol) = strcmp(unitType,unitTypeNames(i));
    switch unitTypeNames(i)
        case {"Noise","MUA"}
            j = find(strcmp(unitTypeNames,unitTypeNames(i))); % 1 (Noise) or 2 (MUA)
            idx(:,typeIdx(j):typeIdx(j+1)-1) = fullIdx(:,typeIdx(j):typeIdx(j+1)-1) & idx(:,UTcol);
        case "Non-Soma MUA" % indexes into 2 (MUA) & 3 (Non-Soma)
            idx(:,typeIdx(2):typeIdx(3+1)-1) = fullIdx(:,typeIdx(2):typeIdx(3+1)-1) & idx(:,UTcol);
        case "Non-Soma Good"
            j = 3; % for indexing in table but not cmap
            idx(:,typeIdx(j):typeIdx(j+1)-1) = fullIdx(:,typeIdx(j):typeIdx(j+1)-1) & idx(:,UTcol);
        otherwise  % i == 3 (Good) No rejection criteria met
    end
    [r, c] = find(idx);
    addStyle(uit,s,"cell",[r, c]) % Label using idx
end

%% Saving the table
% Unfortunately Matlab cannot save the interactive uifigure as a .fig,
% options are to export as a static image or as a table. 
% For now, export as table so it can be used externally (without Matlab)
if exist(fullfile(bombcellFolder,'bombcellReasonOutput.xlsx'))
    overwrite = questdlg('A copy of bombcellReasonOutput.xlsx already exists, Save and overwrite?','Excel file generation','Yes','No','No');
end
if ~exist(fullfile(bombcellFolder,'bombcellReasonOutput.xlsx')) || strcmpi(overwrite,'Yes')
    try % Requires MS Excel and Windows, otherwise fails
        Excel = actxserver('excel.application');  % Create COM server for interfacing with Excel
        disp('Writing data and formatting to bombcellReasonOutput.xlsx ...')
        %Excel.Visible = 1; % Uncomment to show Excel sheet while it is being modified
        writetable(uit.Data,fullfile(bombcellFolder,'bombcellReasonOutput.xlsx'),'WriteMode','overwrite'); % Create and write table using Matlab
        WB = Excel.Workbooks.Open(fullfile(bombcellFolder,'bombcellReasonOutput.xlsx'),0,false); % Open excel file with COM server
        styleConfig = uit.StyleConfigurations;
        for i = 1:height(styleConfig)
            idx = styleConfig.TargetIndex{i}; % Matlab uitable index for style (background colour)
            eIdx = erase(string([char([floor((idx(:,2)-1)/26) mod(idx(:,2)-1,26)+1]+64) num2str(idx(:,1)+1)]),["@" " "]); % Conversion to Excel (A1) indexing format
            col = styleConfig.Style(i).BackgroundColor; % Matlab normalised RGB values
            eCol = sum((col*255) .* [256^0 256^1 256^2]); % Convert to Excel single-value colour (Followed formula)
            for j = 1:length(eIdx)
                WB.Worksheets.Item(1).Range(eIdx(j)).Interior.Color = eCol;
            end
        end
        WB.Save; WB.Close
    catch
        warning("Was unable to save formatted table. Requires MS Excel and Windows, otherwise fails to save")
    end
    disp('bombcellReasonOutput.xlsx has been saved/overwritten')
else
    disp('bombcellReasonOutput.xlsx has not been overwritten')
end
end
