function S = optSchema()
% optSchema  Single-source-of-truth registry of every NGL option.
%
% PURPOSE:
%   Schema-driven replacement for the hand-maintained default_opt.m and
%   the inline asserts inside set_default.m. Each entry bundles
%   (name, default, validator, group, help). The schema is consumed by:
%       generateDefaultsFromSchema -> produces the defaults struct
%       validateOptAgainstSchema   -> (future) replaces set_default Section 2
%       opt_help                    -> CLI lookup of help + default
%       verifySchemaParity          -> parity check vs legacy default_opt
%
% USAGE:
%   S = optSchema();          % schema as a struct array of optEntry
%
% ADDING A NEW OPTION:
%   Append one line below, in the most-fitting group. That is the ONLY
%   file you need to touch. default_opt regenerates from this; set_default
%   (once schema-driven) will pick up the validator automatically.
%
% CROSS-FIELD CHECKS (not in the schema):
%   Rules that depend on more than one option (e.g. stepSz_ms <= binSize_ms,
%   aggregateSubjects implies aggregateSessions, popDyn.alignIdx <=
%   numel(alignto)) live in optPostChecks.m, not here. Keep schema
%   validators purely per-value.
%
% Last modified 09.06.2026 (Jesus)

    S = struct('name',{}, 'default',{}, 'validator',{}, 'group',{}, 'help',{});

    % --- reusable validators -------------------------------------------
    isLog   = @(v) islogical(v) && isscalar(v);
    isPosNS = @(v) isnumeric(v) && isscalar(v) && v > 0;
    isNNNS  = @(v) isnumeric(v) && isscalar(v) && v >= 0;
    isPosIn = @(v) isnumeric(v) && isscalar(v) && v > 0 && v == floor(v);
    inUnit  = @(v) isnumeric(v) && isscalar(v) && v >= 0 && v <= 1;
    isCh    = @(v) ischar(v);
    isCh1   = @(v) ischar(v) && ~isempty(v);
    isCoC   = @(v) iscell(v) && all(cellfun(@ischar, v));
    isNCoC  = @(v) iscell(v) && ~isempty(v) && all(cellfun(@ischar, v));
    isInt2  = @(v) isnumeric(v) && numel(v) == 2 && v(1) < v(2);
    isEoP   = @(v) isempty(v) || (isnumeric(v) && isscalar(v) && v > 0);
    isEoNS  = @(v) isempty(v) || (isnumeric(v) && isscalar(v));
    isNum   = @(v) isnumeric(v);
    isLowpass = @(v) isempty(v) || (isnumeric(v) && isscalar(v) && v > 0 && v < 9500);
    isIsiBins = @(v) isnumeric(v) && isvector(v) && numel(v) >= 2 && all(diff(v) > 0);
    isAny   = @(v) true; %#ok<NASGU>
    isCharOrNumScalar = @(v) ischar(v) || (isnumeric(v) && isscalar(v));
    isWfWin = @(v) isnumeric(v) && numel(v) == 2 && v(1) <= 0 && v(2) > 0;
    isVariants = @(v) iscell(v) && ~isempty(v) && all(cellfun(@ischar, v)) ...
                       && all(ismember(v, {'singleTrials','ciTube'}));
    isTrEmbedMethod = @(v) ischar(v) && ismember(lower(v), {'pca','tsne','umap'});

    % --- Acquisition ----------------------------------------------------
    S(end+1) = optEntry('numChannels', 32, isPosNS, 'Acquisition', ...
        'Expected channel count (override for 32-ch Deuteron).');
    S(end+1) = optEntry('bin', true, isLog, 'Acquisition', ...
        'Check / create the Kilosort .bin file.');
    S(end+1) = optEntry('FieldTrip', true, isLog, 'Acquisition', ...
        'Produce a FieldTrip-ready .mat file.');
    S(end+1) = optEntry('doNWB', true, isLog, 'Acquisition', ...
        'NWB export: INTAN via NeuroConv (Py), Deuteron via matNWB (MATLAB).');

    % --- Events ---------------------------------------------------------
    S(end+1) = optEntry('RetrieveEvents', true, isLog, 'Events', ...
        'Extract event log from session.');
    S(end+1) = optEntry('alignto', {'itiOn'}, isNCoC, 'Events', ...
        'Alignment events; cell array of char vectors.');
    S(end+1) = optEntry('trEvents', {}, isCoC, 'Events', ...
        '''Special'' ITI events (treatments, tutors, etc.).');
    S(end+1) = optEntry('addtime', 0, isNum, 'Events', ...
        'Padding around trial start/end in ms.');
    S(end+1) = optEntry('uselog', false, isLog, 'Events', ...
        'Use Deuteron text log instead of data files for events.');

    % --- Motion sensors -------------------------------------------------
    S(end+1) = optEntry('GetMotionSensors', false, isLog, 'Motion', ...
        'Extract head-direction sensor data.');

    % --- Preprocessing filters -----------------------------------------
    S(end+1) = optEntry('noise', [], @(v) true, 'Preprocessing', ...
        'Reserved for noise-rejection parameters.');
    S(end+1) = optEntry('lowpass', 9000, isLowpass, 'Preprocessing', ...
        '.bin low-pass (Hz, < 9500). [] = off.');
    S(end+1) = optEntry('lowpassFT', 200, isPosNS, 'Preprocessing', ...
        'Low-pass for FieldTrip LFP stream (Hz).');
    S(end+1) = optEntry('highpass', [], isEoP, 'Preprocessing', ...
        '.bin high-pass (Hz). [] = off.');
    S(end+1) = optEntry('linefilter', 0, isNNNS, 'Preprocessing', ...
        'Line-noise notch centre frequency. 0 = off.');
    S(end+1) = optEntry('CAR', 0, isNum, 'Preprocessing', ...
        'Common-average re-referencing. 0 = off.');
    S(end+1) = optEntry('dwnsmplRate', [], isEoP, 'Preprocessing', ...
        'LFP downsample target (Hz). [] = auto (937.5 Hz).');
    S(end+1) = optEntry('timebreak', false, isLog, 'Preprocessing', ...
        'Expect a break in the recording (e.g. Deuteron battery change).');

    % --- Sorting & curation --------------------------------------------
    S(end+1) = optEntry('kilosort', true, isLog, 'Sorting', ...
        'Run Kilosort 4.');
    S(end+1) = optEntry('KSchanMapFile', '', isCh, 'Sorting', ...
        'Empty = linear array; or set to e.g. ''chanMapXXX.mat''.');
    S(end+1) = optEntry('bombcell', true, isLog, 'Sorting', ...
        'Run Bombcell QC on Kilosort output.');
    S(end+1) = optEntry('callBcGUI', false, isLog, 'Sorting', ...
        'Open Bombcell GUI after QC.');
    S(end+1) = optEntry('phy', false, isLog, 'Sorting', ...
        'Open Phy right after sorting (BLOCKS MATLAB).');

    % --- NGL02 stage gates ---------------------------------------------
    S(end+1) = optEntry('doSpikething', true, isLog, 'NGL02 gates', ...
        'Process single-unit / spike data in NGL02_postPhy.');
    S(end+1) = optEntry('doLFPthing', true, isLog, 'NGL02 gates', ...
        'Process LFP data in NGL02_LFP.');

    % --- Spike side: video + social tracking ---------------------------
    S(end+1) = optEntry('offlineTrack', false, isLog, 'Spike side', ...
        'Run offline video blob detection (social-arena projects).');
    S(end+1) = optEntry('useTrack', false, isLog, 'Spike side', ...
        'Index spiking against social-tracking events.');

    % --- LFP side gates ------------------------------------------------
    S(end+1) = optEntry('trialparsed', false, isLog, 'LFP side', ...
        'Load trial-parsed FT file (vs continuous).');
    S(end+1) = optEntry('artifdet', false, isLog, 'LFP side', ...
        'Run LFP artifact detection and rejection.');
    S(end+1) = optEntry('artZvalue', 10, isPosNS, 'LFP side', ...
        'Z-value cutoff for ft_artifact_zvalue.');
    S(end+1) = optEntry('rejValue', 'zero', isCharOrNumScalar, 'LFP side', ...
        'Fill value for rejected segments: ''zero''|''nan''|numeric.');
    S(end+1) = optEntry('spectrogram', false, isLog, 'LFP side', ...
        'Run multitaper time-frequency analysis.');

    % --- Legacy ---------------------------------------------------------
    S(end+1) = optEntry('neurDyn.do', false, isLog, 'Legacy', ...
        'LEGACY trial-state embedding; superseded by opt.popDyn.trialEmbed.');

    % --- Population dynamics ------------------------------------------
    S(end+1) = optEntry('popDyn.do', false, isLog, 'PopDyn', ...
        'Master gate: run any population-dynamics step.');
    S(end+1) = optEntry('popDyn.pca', true, isLog, 'PopDyn', ...
        'Per-session PCA via calculate_pca_from_pool (single-trial overlay + CI tube).');
    S(end+1) = optEntry('popDyn.jPCA', false, isLog, 'PopDyn', ...
        'Rotational dynamics (PLACEHOLDER).');
    S(end+1) = optEntry('popDyn.GPFA', false, isLog, 'PopDyn', ...
        'Single-trial smooth trajectories (PLACEHOLDER).');
    S(end+1) = optEntry('popDyn.trialEmbed', false, isLog, 'PopDyn', ...
        'Legacy trial-similarity embedding (PCA/tSNE/UMAP per trial).');
    S(end+1) = optEntry('popDyn.smoothSigma', 0.050, isNNNS, 'PopDyn', ...
        'Gaussian smoothing sigma in SECONDS (~50 ms default).');
    S(end+1) = optEntry('popDyn.nComponents', 3, isPosIn, 'PopDyn', ...
        'Output embedding dimensionality.');
    S(end+1) = optEntry('popDyn.conditionVar', '', isCh, 'PopDyn', ...
        'Field name on condition for per-condition grouping (empty = no grouping).');
    S(end+1) = optEntry('popDyn.dropAborted', true, isLog, 'PopDyn', ...
        'Drop aborted trials before grouping (matches legacy FR filter).');
    S(end+1) = optEntry('popDyn.alignIdx', 1, isPosIn, 'PopDyn', ...
        'Index into opt.alignto (ignored by the new PCA path; kept for placeholders).');
    S(end+1) = optEntry('popDyn.trialEmbedMethod', 'tSNE', isTrEmbedMethod, 'PopDyn', ...
        'trialEmbed method: ''PCA''|''tSNE''|''UMAP''.');
    S(end+1) = optEntry('popDyn.pcaConditions', {'allInitiated'}, isNCoC, 'PopDyn', ...
        'Cell of condition tokens (single or ''X vs Y'') iterated by per-session PCA.');

    % --- Waveform extraction ------------------------------------------
    S(end+1) = optEntry('getwF', false, isLog, 'Waveform', ...
        'Extract raw waveforms per cluster (slow).');
    S(end+1) = optEntry('gwfparams.wfWin', [-20 41], isWfWin, 'Waveform', ...
        'Samples around spiketime [pre post] with pre<=0<post.');
    S(end+1) = optEntry('gwfparams.nWf', 2000, isPosIn, 'Waveform', ...
        'Max waveforms per cluster.');
    S(end+1) = optEntry('gwfparams.dataType', 'int16', isCh, 'Waveform', ...
        '.bin sample type (overridden by loadSpikes).');
    S(end+1) = optEntry('gwfparams.nCh', [], isEoP, 'Waveform', ...
        'Set inside loadSpikes from spikes.n_channels_dat.');

    % --- Cluster loading + ISI binning --------------------------------
    S(end+1) = optEntry('spparams.excludeNoise', true, isLog, 'Spike loading', ...
        'Skip Phy ''noise''-labelled clusters.');
    S(end+1) = optEntry('spparams.loadPCs', false, isLog, 'Spike loading', ...
        'Load principal components (rarely needed).');
    S(end+1) = optEntry('isibins', 0:0.5:200, isIsiBins, 'Spike loading', ...
        'ISI histogram bin edges (ms) — strictly increasing vector, >=2 entries.');

    % --- Canonical FR binning -----------------------------------------
    S(end+1) = optEntry('binSize_ms', 200, isPosNS, 'FR binning', ...
        'FR sliding-bin width (ms).');
    S(end+1) = optEntry('stepSz_ms', 20, isPosNS, 'FR binning', ...
        'FR sliding-bin step (ms).');

    % --- Per-area context (set internally) ----------------------------
    S(end+1) = optEntry('area', 'all', isCh1, 'Per-area', ...
        'NGL02 sets this per area; default ''all''.');

    % --- Project-specific gates ---------------------------------------
    S(end+1) = optEntry('proj_chgDtctPCue', false, isLog, 'Project gates', ...
        'Change-Detection P-Cue paradigm (trialdef /32).');
    S(end+1) = optEntry('proj_socialLearning', false, isLog, 'Project gates', ...
        'SocialLearning ASL (TFR testname, etc.).');
    S(end+1) = optEntry('proj_extintion', false, isLog, 'Project gates', ...
        'Extintion paradigm (fireRate_extintion, trialdef -1000 offset).');
    S(end+1) = optEntry('proj_FLIP', false, isLog, 'Project gates', ...
        'vFLIP laminar power analysis.');

    % --- NGL04_fireRate (PSTH plotter) --------------------------------
    S(end+1) = optEntry('fireRatePlot.interval', [-2000 4000], isInt2, 'NGL04_fireRate', ...
        'MS window around alignment passed to plotPSTH.');
    S(end+1) = optEntry('fireRatePlot.binSize_ms', 200, isPosNS, 'NGL04_fireRate', ...
        'FR bin width inside the plot.');
    S(end+1) = optEntry('fireRatePlot.stepSz_ms', 20, isPosNS, 'NGL04_fireRate', ...
        'FR bin step inside the plot (must be <= fireRatePlot.binSize_ms).');
    S(end+1) = optEntry('fireRatePlot.smoothPlot', true, isLog, 'NGL04_fireRate', ...
        'nanMeanSterrHistogram smoothing.');
    S(end+1) = optEntry('fireRatePlot.errAlpha', 0.4, inUnit, 'NGL04_fireRate', ...
        'Error-shade alpha (0..1).');
    S(end+1) = optEntry('fireRatePlot.labelPriority', {'HumanLabel','KSLabel','bc_unitType'}, isNCoC, 'NGL04_fireRate', ...
        'Resolution order for cluster-label tokens.');
    S(end+1) = optEntry('fireRatePlot.busyWarnTraces', 4, isPosNS, 'NGL04_fireRate', ...
        'Warn above N overlaid traces per subplot.');
    S(end+1) = optEntry('fireRatePlot.outDir', '', isCh, 'NGL04_fireRate', ...
        'Empty -> default <input.analysis>/plots/NGL04_fireRate.');
    S(end+1) = optEntry('fireRatePlot.cacheDir', '', isCh, 'NGL04_fireRate', ...
        'Empty -> default <input.analysis>/cache/firepools (shared with NGL04_PCA).');

    % --- NGL04_PCA (state-space plotter) ------------------------------
    S(end+1) = optEntry('pcaPlot.interval', [-2000 4000], isInt2, 'NGL04_PCA', ...
        'MS window around alignment.');
    S(end+1) = optEntry('pcaPlot.binSize_ms', 200, isPosNS, 'NGL04_PCA', ...
        'FR bin width (ms).');
    S(end+1) = optEntry('pcaPlot.stepSz_ms', 20, isPosNS, 'NGL04_PCA', ...
        'FR bin step (ms, must be <= pcaPlot.binSize_ms).');
    S(end+1) = optEntry('pcaPlot.smoothSigma_s', 0.050, isNNNS, 'NGL04_PCA', ...
        'Gaussian sigma for smoothing (s).');
    S(end+1) = optEntry('pcaPlot.nComponents', 3, @(v) isnumeric(v) && isscalar(v) && v >= 2, 'NGL04_PCA', ...
        'Number of PCs to keep (>=2).');
    S(end+1) = optEntry('pcaPlot.nBootstrap', 100, isNNNS, 'NGL04_PCA', ...
        'Trial-bootstrap reps for CI tube; 0 disables.');
    S(end+1) = optEntry('pcaPlot.rngSeed', [], isEoNS, 'NGL04_PCA', ...
        'Integer seed for reproducible CI, or [] for random.');
    S(end+1) = optEntry('pcaPlot.sessionAlpha', 0.18, inUnit, 'NGL04_PCA', ...
        'Alpha for grey single-trial / session-marginal traces.');
    S(end+1) = optEntry('pcaPlot.ciAlpha', 0.20, inUnit, 'NGL04_PCA', ...
        'Alpha for 2D CI ribbon.');
    S(end+1) = optEntry('pcaPlot.ciStride', 10, isPosNS, 'NGL04_PCA', ...
        '3D CI crosshair every N bins.');
    S(end+1) = optEntry('pcaPlot.variants', {'singleTrials','ciTube'}, isVariants, 'NGL04_PCA', ...
        'Which figure variants to render.');
    S(end+1) = optEntry('pcaPlot.outDir', '', isCh, 'NGL04_PCA', ...
        'Empty -> NGL04_PCA defaults to <input.analysis>/plots/PCA; per-session calculate_neural_pca writes to <opt.analysis>/plots/population_dynamics.');

    % --- Gaze / video pipeline (GazEstim via process_gaze) ------------
    % Process_gaze is a wrapper around the GazEstim Python toolbox
    % (toolboxes/GazEstim/{pose_clean,pose_render}.py via configfiles/
    % master_gaze.py). All knobs below are forwarded to the JSON config
    % the wrapper hands to master_gaze.py. Project-default values live
    % here; per-run overrides go in the params struct passed to
    % process_gaze() (typically by NGL06_VideoProcess).
    S(end+1) = optEntry('gaze.do', false, isLog, 'Gaze', ...
        'Master gate: process_gaze runs on each discovered DLC csv.');
    S(end+1) = optEntry('gaze.fps', 59.94, isPosNS, 'Gaze', ...
        'Input video frame rate (Hz).');
    S(end+1) = optEntry('gaze.downsampleStep', 2, isPosIn, 'Gaze', ...
        'Keep 1 frame per N; out_fps = fps/N.');
    S(end+1) = optEntry('gaze.pCut', 0.5, inUnit, 'Gaze', ...
        'DLC likelihood gate (0..1).');
    S(end+1) = optEntry('gaze.devFac', 0.6, isNNNS, 'Gaze', ...
        'Jump threshold = devFac * bodyLength.');
    S(end+1) = optEntry('gaze.smooth', 5, isPosIn, 'Gaze', ...
        'Temporal smoothing window (frames).');
    S(end+1) = optEntry('gaze.wMed', 9, isPosIn, 'Gaze', ...
        'Rolling-median window (frames).');
    S(end+1) = optEntry('gaze.boneTolFrac', 0.4, isNNNS, 'Gaze', ...
        'Bone-length tolerance fraction.');
    S(end+1) = optEntry('gaze.boneTolMad', 5.0, isNNNS, 'Gaze', ...
        'Bone-length tolerance (xMAD).');
    S(end+1) = optEntry('gaze.orderMargin', 0.10, isNNNS, 'Gaze', ...
        'Head-behind-wing clamp margin (xbody).');
    S(end+1) = optEntry('gaze.videoWidth', 1250, isPosIn, 'Gaze', ...
        'Source video width in pixels (matches DLC training).');
    S(end+1) = optEntry('gaze.videoHeight', 1160, isPosIn, 'Gaze', ...
        'Source video height in pixels.');
    S(end+1) = optEntry('gaze.drawCones', true, isLog, 'Gaze', ...
        'Render gaze cones on the output video.');
    S(end+1) = optEntry('gaze.monoFOV', 170, isPosNS, 'Gaze', ...
        'Monocular field per eye (degrees).');
    S(end+1) = optEntry('gaze.binoHalf', 15, isNNNS, 'Gaze', ...
        'Binocular half-angle (degrees).');
    S(end+1) = optEntry('gaze.coneMult', 2.5, isPosNS, 'Gaze', ...
        'Cone length = coneMult * birdLength.');
    S(end+1) = optEntry('gaze.eyeFwdFrac', 1/3, isNNNS, 'Gaze', ...
        'Eye base: fraction of head->beak from head.');
    S(end+1) = optEntry('gaze.eyeLatFrac', 1/5, isNNNS, 'Gaze', ...
        'Eye lateral offset: fraction of back->wing.');
    S(end+1) = optEntry('gaze.dpi', 120, isPosIn, 'Gaze', ...
        'Render DPI (encoding).');
    S(end+1) = optEntry('gaze.crf', 24, isPosIn, 'Gaze', ...
        'ffmpeg CRF quality (lower = better, larger files).');
    S(end+1) = optEntry('gaze.preset', 'veryfast', isCh, 'Gaze', ...
        'ffmpeg preset (e.g. ''ultrafast'' / ''veryfast'' / ''medium'').');
    S(end+1) = optEntry('gaze.background', '', isCh, 'Gaze', ...
        'Background image path. Empty -> <analysisCode>/HexArena.png then configfiles/HexArena.png.');
    S(end+1) = optEntry('gaze.masterScript', '', isCh, 'Gaze', ...
        'master_gaze.py path. Empty -> <analysisCode>/master_gaze.py then configfiles/master_gaze.py.');

    % --- Cross-session aggregation (NGL03_acrossSession) --------------
    S(end+1) = optEntry('aggregateSessions', false, isLog, 'Aggregation', ...
        'Build <subject>_aggregated.mat per subject.');
    S(end+1) = optEntry('aggregateSubjects', false, isLog, 'Aggregation', ...
        'Build study-level aggregated.mat across subjects (requires aggregateSessions).');
end
