function S = optSchema()
% optSchema  Single-source-of-truth registry of every NGL option.
%
% PURPOSE:
%   Schema-driven replacement for the hand-maintained default_opt.m and
%   the inline asserts inside set_default.m. Each entry bundles
%   (name, default, validator, group, help). The schema is consumed by:
%       generateDefaultsFromSchema -> produces the defaults struct
%       validateOptAgainstSchema   -> (future) replaces set_default Section 2
%       opt_help                    -> CLI lookup of help + default
%       verifySchemaParity          -> parity check vs legacy default_opt
%
% USAGE:
%   S = optSchema();          % schema as a struct array of optEntry
%
% ADDING A NEW OPTION:
%   Append one line below, in the most-fitting group. That is the ONLY
%   file you need to touch. default_opt regenerates from this; set_default
%   (once schema-driven) will pick up the validator automatically.
%
% CROSS-FIELD CHECKS (not in the schema):
%   Rules that depend on more than one option (e.g. stepSz_ms <= binSize_ms,
%   aggregateSubjects implies aggregateSessions, popDyn.alignIdx <=
%   numel(alignto)) live in optPostChecks.m, not here. Keep schema
%   validators purely per-value.
%
% Last modified 09.06.2026 (Jesus)

    S = struct('name',{}, 'default',{}, 'validator',{}, 'group',{}, 'help',{});

    % --- reusable validators -------------------------------------------
    isLog   = @(v) islogical(v) && isscalar(v);
    isPosNS = @(v) isnumeric(v) && isscalar(v) && v > 0;
    isNNNS  = @(v) isnumeric(v) && isscalar(v) && v >= 0;
    isPosIn = @(v) isnumeric(v) && isscalar(v) && v > 0 && v == floor(v);
    inUnit  = @(v) isnumeric(v) && isscalar(v) && v >= 0 && v <= 1;
    isCh    = @(v) ischar(v);
    isCh1   = @(v) ischar(v) && ~isempty(v);
    isLogOrCh = @(v) (islogical(v) && isscalar(v)) || ischar(v);
    isCoC   = @(v) iscell(v) && all(cellfun(@ischar, v));
    isNCoC  = @(v) iscell(v) && ~isempty(v) && all(cellfun(@ischar, v));
    isInt2  = @(v) isnumeric(v) && numel(v) == 2 && v(1) < v(2);
    isEoP   = @(v) isempty(v) || (isnumeric(v) && isscalar(v) && v > 0);
    isEoNS  = @(v) isempty(v) || (isnumeric(v) && isscalar(v));
    isNum   = @(v) isnumeric(v);
    isLowpass = @(v) isempty(v) || (isnumeric(v) && isscalar(v) && v > 0 && v < 9500);
    isIsiBins = @(v) isnumeric(v) && isvector(v) && numel(v) >= 2 && all(diff(v) > 0);
    isAny   = @(v) true; %#ok<NASGU>
    isCharOrNumScalar = @(v) ischar(v) || (isnumeric(v) && isscalar(v));
    isWfWin = @(v) isnumeric(v) && numel(v) == 2 && v(1) <= 0 && v(2) > 0;
    isVariants = @(v) iscell(v) && ~isempty(v) && all(cellfun(@ischar, v)) ...
                       && all(ismember(v, {'singleTrials','ciTube'}));
    isTrEmbedMethod = @(v) ischar(v) && ismember(lower(v), {'pca','tsne','umap'});

    % --- Acquisition ----------------------------------------------------
    S(end+1) = optEntry('numChannels', 32, isPosNS, 'Acquisition', ...
        'Expected channel count (override for 32-ch Deuteron).');
    S(end+1) = optEntry('bin', true, isLog, 'Acquisition', ...
        'Check / create the Kilosort .bin file.');
    S(end+1) = optEntry('FieldTrip', true, isLog, 'Acquisition', ...
        'Produce a FieldTrip-ready .mat file.');
    S(end+1) = optEntry('doNWB', true, isLog, 'Acquisition', ...
        'NWB export: INTAN via NeuroConv (Py), Deuteron via matNWB (MATLAB).');

    % --- Events ---------------------------------------------------------
    S(end+1) = optEntry('RetrieveEvents', true, isLog, 'Events', ...
        'Extract event log from session.');
    S(end+1) = optEntry('alignto', {'itiOn'}, isNCoC, 'Events', ...
        'Alignment events; cell array of char vectors.');
    S(end+1) = optEntry('trEvents', {}, isCoC, 'Events', ...
        '''Special'' ITI events (treatments, tutors, etc.).');
    S(end+1) = optEntry('addtime', 0, isNum, 'Events', ...
        'Padding around trial start/end in ms.');
    S(end+1) = optEntry('uselog', false, isLog, 'Events', ...
        'Use Deuteron text log instead of data files for events.');

    % --- Motion sensors -------------------------------------------------
    S(end+1) = optEntry('GetMotionSensors', false, isLog, 'Motion', ...
        'Extract head-direction sensor data.');

    % --- Preprocessing filters -----------------------------------------
    S(end+1) = optEntry('noise', [], @(v) true, 'Preprocessing', ...
        'Reserved for noise-rejection parameters.');
    S(end+1) = optEntry('lowpass', 9000, isLowpass, 'Preprocessing', ...
        '.bin low-pass (Hz, < 9500). [] = off.');
    S(end+1) = optEntry('lowpassFT', 200, isPosNS, 'Preprocessing', ...
        'Low-pass for FieldTrip LFP stream (Hz).');
    S(end+1) = optEntry('highpass', [], isEoP, 'Preprocessing', ...
        '.bin high-pass (Hz). [] = off.');
    S(end+1) = optEntry('linefilter', 0, isNNNS, 'Preprocessing', ...
        'Line-noise notch centre frequency. 0 = off.');
    S(end+1) = optEntry('CAR', 0, isNum, 'Preprocessing', ...
        'Common-average re-referencing. 0 = off.');
    S(end+1) = optEntry('dwnsmplRate', [], isEoP, 'Preprocessing', ...
        'LFP downsample target (Hz). [] = auto (937.5 Hz).');
    S(end+1) = optEntry('timebreak', false, isLog, 'Preprocessing', ...
        'Expect a break in the recording (e.g. Deuteron battery change).');

    % --- Sorting & curation --------------------------------------------
    S(end+1) = optEntry('kilosort', true, isLog, 'Sorting', ...
        'Run Kilosort 4.');
    S(end+1) = optEntry('KSchanMapFile', '', isCh, 'Sorting', ...
        'Empty = linear array; or set to e.g. ''chanMapXXX.mat''.');
    S(end+1) = optEntry('bombcell', true, isLog, 'Sorting', ...
        'Run Bombcell QC on Kilosort output.');
    S(end+1) = optEntry('callBcGUI', false, isLog, 'Sorting', ...
        'Open Bombcell GUI after QC.');
    S(end+1) = optEntry('phy', false, isLog, 'Sorting', ...
        'Open Phy right after sorting (BLOCKS MATLAB).');

    % --- NGL02 stage gates ---------------------------------------------
    S(end+1) = optEntry('doSpikething', true, isLog, 'NGL02 gates', ...
        'Process single-unit / spike data in NGL02_postPhy.');
    S(end+1) = optEntry('doLFPthing', true, isLog, 'NGL02 gates', ...
        'Process LFP data in NGL02_LFP.');

    % --- Spike side: video + social tracking ---------------------------
    S(end+1) = optEntry('offlineTrack', false, isLog, 'Spike side', ...
        'Run offline video blob detection (social-arena projects).');
    S(end+1) = optEntry('useTrack', false, isLog, 'Spike side', ...
        'Index spiking against social-tracking events.');

    % --- LFP side gates ------------------------------------------------
    S(end+1) = optEntry('trialparsed', false, isLog, 'LFP side', ...
        'Load trial-parsed FT file (vs continuous).');
    S(end+1) = optEntry('artifdet', false, isLog, 'LFP side', ...
        'Run LFP artifact detection and rejection.');
    S(end+1) = optEntry('artZvalue', 10, isPosNS, 'LFP side', ...
        'Z-value cutoff for ft_artifact_zvalue.');
    S(end+1) = optEntry('rejValue', 'zero', isCharOrNumScalar, 'LFP side', ...
        'Fill value for rejected segments: ''zero''|''nan''|numeric.');
    S(end+1) = optEntry('spectrogram', false, isLog, 'LFP side', ...
        'Run multitaper time-frequency analysis.');

    % LFP side (Pass 1 schema honesty, 26.06.2026) - nine fields consumed
    % by trialparsed_MTspectrogram / plot_superletsTFR_* that were never
    % declared. Kept flat for symmetry with the existing LFP-side entries;
    % the opt.lfp.* rename lands in Pass 2 along with the split of
    % trialparsed_MTspectrogram into a generic core plus project-specific
    % wrappers.
    isCellOfNumVec = @(v) iscell(v) && all(cellfun(@(x) isnumeric(x) && isvector(x) && ~isempty(x), v));
    isBlocksSpec   = @(v) (ischar(v) && strcmpi(v,'all')) || ...
                          (isnumeric(v) && isscalar(v) && v >= 1 && v == floor(v));
    isTFRmethod    = @(v) ischar(v) && ismember(lower(v), {'wavelet','mtmconvol','superlet'});
    isCellOfNumVecOrEmpty = @(v) isempty(v) || isCellOfNumVec(v);

    S(end+1) = optEntry('freqInterest', {}, isCellOfNumVecOrEmpty, 'LFP side', ...
        ['Cell of frequency vectors, one per band (e.g. {[4:1:30], [30:2:150]}). ', ...
         'Empty -> user must set before running trialparsed_MTspectrogram.']);
    S(end+1) = optEntry('TFRmethod', 'wavelet', isTFRmethod, 'LFP side', ...
        'ft_freqanalysis method: ''wavelet'' (Morlet) | ''mtmconvol'' (multitaper) | ''superlet''.');
    S(end+1) = optEntry('superletOrder', {}, isCellOfNumVecOrEmpty, 'LFP side', ...
        'Superlet order per band (cell, matches freqInterest length). Only consulted when TFRmethod = ''superlet''.');
    S(end+1) = optEntry('width', {}, isCellOfNumVecOrEmpty, 'LFP side', ...
        'Superlet width per band (cell, matches freqInterest length). Only consulted when TFRmethod = ''superlet''.');
    S(end+1) = optEntry('combine', 'additive', isCh, 'LFP side', ...
        'Superlet combine mode: ''additive''|''multiplicative''. Only consulted when TFRmethod = ''superlet''.');
    S(end+1) = optEntry('timeResol', 0.1, isPosNS, 'LFP side', ...
        'TFR time-of-interest step (s). e.g. cfg.toi = opt.toi(1):timeResol:opt.toi(2).');
    S(end+1) = optEntry('toi', [-0.5 4], isInt2, 'LFP side', ...
        'TFR time-of-interest range [t0 t1] (seconds relative to alignment). Feeds cfg.toi in computeTrialparsedTFR. Default tightened 26.06.2026 from [-4 8] to [-0.5 4] to cut compute.');
    S(end+1) = optEntry('blocks', 'all', isBlocksSpec, 'LFP side', ...
        '''all'' -> derive from condition.block; positive integer N -> iterate over N blocks. Used by the ASL trial-parsed path.');
    S(end+1) = optEntry('chbych', false, isLog, 'LFP side', ...
        'Trigger channel-by-channel TFR plotting (plot_superletsTFR_extintion_chbych).');
    S(end+1) = optEntry('trialbytrial', false, isLog, 'LFP side', ...
        'Trigger trial-by-trial TFR plotting (plot_superletsTFR_extintion_tbt).');

    % LFP side (Pass 2, 26.06.2026) - two knobs consumed by the generic
    % computeTrialparsedTFR core. Grouped under opt.lfp.* per the Pass 2
    % nesting convention; the older flat LFP entries above are being
    % migrated toward opt.lfp.* incrementally.
    isCharOrCell = @(v) isempty(v) || ischar(v) || (iscell(v) && all(cellfun(@ischar, v)));
    S(end+1) = optEntry('lfp.tfrAreaFilter', '', isCharOrCell, 'LFP side', ...
        ['Restrict TFR computation to a subset of channels by ', ...
         'FT_data.chanArea. char or cellstr (e.g. ''NCL'' or {''NCL'',''STR''}). ', ...
         'Empty -> all channels (single-area default).']);
    S(end+1) = optEntry('lfp.tfrCacheDir', '', isCh, 'LFP side', ...
        'Override for the TFR cache folder. Empty -> <opt.analysis>/cache/lfp_tfr/.');
    S(end+1) = optEntry('lfp.alignSubset', {}, isCoC, 'LFP side', ...
        ['Cellstr subset of opt.alignto to process on the LFP path only. ', ...
         'Empty -> use opt.alignto verbatim. Trial-parsed TFR is expensive; ', ...
         'this lets you e.g. run LFP TFR only for {''itiOn''} while keeping ', ...
         'spike-side analyses over the whole alignment list.']);

    % TFR performance knobs (Pass 3 follow-up, 26.06.2026; auto-suite 27.06.2026).
    isParallelMode = @(v) ischar(v) && ismember(lower(v), {'none','bands','trials'});
    S(end+1) = optEntry('lfp.downsampleFs', [], isEoP, 'LFP side', ...
        ['Target sample rate (Hz) for ft_resampledata BEFORE ft_freqanalysis. ', ...
         'Empty -> compute per band from opt.lfp.autoDownsampleFactor * max(band). ', ...
         'Set explicitly to override the per-band auto choice.']);
    S(end+1) = optEntry('lfp.autoDownsample', true, isLog, 'LFP side', ...
        ['When true, computeTrialparsedTFR picks a per-BAND target sample rate = ', ...
         'ceil(autoDownsampleFactor * max(band)) and calls ft_resampledata on a ', ...
         'working copy of the FT before ft_freqanalysis. Big win (5-10x on the low ', ...
         'band). Set false to keep the source rate.']);
    S(end+1) = optEntry('lfp.autoDownsampleFactor', 4, isPosNS, 'LFP side', ...
        ['Nyquist safety factor for autoDownsample. Target Fs per band = ', ...
         'ceil(autoDownsampleFactor * max(band)). Default 4x is generous (Nyquist ', ...
         'requires 2x); 3x is aggressive, 5x extra safe.']);
    S(end+1) = optEntry('lfp.autoMethod', true, isLog, 'LFP side', ...
        ['When true, opt.TFRmethod is treated as the DEFAULT and can be overridden ', ...
         'per band by the auto rule: any band with max(band) <= 30 Hz gets ', ...
         '''mtmconvol'' + hanning (FT''s recommended low-freq path; typically 2-3x ', ...
         'faster than wavelet width=7). Bands above 30 Hz keep opt.TFRmethod.']);
    S(end+1) = optEntry('lfp.autoMethodThresholdHz', 30, isPosNS, 'LFP side', ...
        'Freq cutoff (Hz) below which autoMethod uses mtmconvol+hanning.');
    S(end+1) = optEntry('lfp.autoFoi', true, isLog, 'LFP side', ...
        ['When true, computeTrialparsedTFR replaces the user-supplied linear foi ', ...
         'vectors with quarter-octave log-spaced foi vectors spanning ', ...
         '[min(band) max(band)]. Preserves visual band coverage but cuts oversampling ', ...
         'at high freqs where the wavelet bandwidth is already several Hz wide. ', ...
         'Typically halves nFreq per band.']);
    S(end+1) = optEntry('lfp.autoFoiStep', 1/4, isPosNS, 'LFP side', ...
        ['Log-spacing step in OCTAVES. Default 1/4 (quarter octave; factor 2^(1/4) ', ...
         '~ 1.19). Use 1/6 for denser, 1/2 for half-octave (coarser).']);
    S(end+1) = optEntry('lfp.parallel', 'trials', isParallelMode, 'LFP side', ...
        ['TFR parallelisation mode. ''none'' -> serial. ''bands'' -> parfor over ', ...
         'opt.freqInterest bands (best when nBands >= nWorkers, no PCT dependency ', ...
         'beyond a parpool being open). ''trials'' -> passes cfg.parallel = parpool ', ...
         'to ft_freqanalysis for per-trial distribution inside each band (best when ', ...
         'nBands < nWorkers; requires Parallel Computing Toolbox). ''bands'' and ', ...
         '''trials'' do NOT compose - pick one per configuration. Default changed ', ...
         '26.06.2026 from ''none'' to ''trials'' to hit all cores by default.']);

    % --- NGL07_LFPanalysis (session-level rich stage; Pass 3) ----------
    % Master gate + per-analysis gates. All default off - NGL07 does
    % nothing unless the master gate flips and at least one analysis
    % gate is on.
    isBands = @(v) iscell(v) && all(cellfun(@(b) iscell(b) && numel(b)==2 && ...
                        ischar(b{1}) && isnumeric(b{2}) && numel(b{2})==2, v));
    S(end+1) = optEntry('lfp.session.do', false, isLog, 'LFP side', ...
        'NGL07_LFPanalysis master gate: run the session-level LFP research stage.');
    S(end+1) = optEntry('lfp.session.tfr', true, isLog, 'LFP side', ...
        'NGL07: run trial-parsed TFR (uses computeTrialparsedTFR per opt.alignto).');
    S(end+1) = optEntry('lfp.session.bursts', false, isLog, 'LFP side', ...
        'NGL07: run detectBursts per opt.lfp.bands.');
    S(end+1) = optEntry('lfp.session.phase', false, isLog, 'LFP side', ...
        'NGL07: run hilbertBandpass to save continuous phase + envelope per band.');
    S(end+1) = optEntry('lfp.session.spikeField', false, isLog, 'LFP side', ...
        'NGL07: run spikeFieldCoupling per cluster (needs NGL02_postPhy output).');
    S(end+1) = optEntry('lfp.session.behReg', false, isLog, 'LFP side', ...
        'NGL07: run lfpBehaviorRegression (STUB until NGL06 emits gaze.mat sidecar).');
    S(end+1) = optEntry('lfp.session.flip', false, isLog, 'LFP side', ...
        'NGL07: run spectrolaminarFLIP per configured area.');

    % Band definitions (used by detectBursts + hilbertBandpass + planned
    % NGL07 spike-phase analyses).
    S(end+1) = optEntry('lfp.bands', ...
        {{'theta',[4 8]}, {'beta',[15 30]}, {'gamma',[30 90]}}, isBands, 'LFP side', ...
        'Cell of {name, [flo fhi]} rows. Default = theta / beta / gamma.');

    % Burst detector.
    S(end+1) = optEntry('lfp.burst.threshMult', 3, isPosNS, 'LFP side', ...
        'detectBursts z-sigma threshold on log-envelope.');
    S(end+1) = optEntry('lfp.burst.minDurationMs', 100, isPosNS, 'LFP side', ...
        'detectBursts minimum episode duration (ms).');

    % Spike-field coupling.
    isPPCmethod = @(v) ischar(v) && ismember(lower(v), {'ppc0','ppc1','ppc2'});
    S(end+1) = optEntry('lfp.spikeField.minSpikes', 50, isPosIn, 'LFP side', ...
        'spikeFieldCoupling: skip clusters with fewer than this many spikes.');
    S(end+1) = optEntry('lfp.spikeField.ppcMethod', 'ppc2', isPPCmethod, 'LFP side', ...
        'spikeFieldCoupling: PPC estimator (Vinck et al. 2010/2011).');
    S(end+1) = optEntry('lfp.spikeField.timwin', 0.5, isPosNS, 'LFP side', ...
        'spikeFieldCoupling: STA window (s) around each spike.');
    S(end+1) = optEntry('lfp.spikeField.foi', 2:2:100, isNum, 'LFP side', ...
        'spikeFieldCoupling: coherence frequency vector (Hz).');

    % Hilbert phase / envelope storage.
    S(end+1) = optEntry('lfp.hilbert.storePhase', true, isLog, 'LFP side', ...
        'hilbertBandpass: save the [nCh x nSamples] phase matrix per band.');
    S(end+1) = optEntry('lfp.hilbert.storeEnv', true, isLog, 'LFP side', ...
        'hilbertBandpass: save the [nCh x nSamples] envelope matrix per band.');
    S(end+1) = optEntry('lfp.hilbert.dtype', 'single', isCh, 'LFP side', ...
        'hilbertBandpass: storage dtype for phase/envelope (''single'' halves file size vs ''double'').');

    % vFLIP.
    S(end+1) = optEntry('lfp.flip.laminaraxis', 0:0.05:1.55, isNum, 'LFP side', ...
        'spectrolaminarFLIP: probe laminar axis (mm), length == nChans per bank.');
    S(end+1) = optEntry('lfp.flip.freqaxis', 1:150, isNum, 'LFP side', ...
        'spectrolaminarFLIP: frequency axis (Hz).');
    S(end+1) = optEntry('lfp.flip.setfreqbool', 0, isNum, 'LFP side', ...
        'spectrolaminarFLIP: 0 = vFLIP (auto-tune bands), 1 = default fixed FLIP bands.');

    % Behavior regression (NGL06 sidecar required).
    S(end+1) = optEntry('lfp.behReg.covariates', {'x','y','head_dir'}, isNCoC, 'LFP side', ...
        'lfpBehaviorRegression: covariate names from the NGL06 gaze.mat sidecar.');
    S(end+1) = optEntry('lfp.behReg.numrand', 1000, isPosIn, 'LFP side', ...
        'lfpBehaviorRegression: cluster-perm test permutations.');
    S(end+1) = optEntry('lfp.behReg.alpha', 0.05, inUnit, 'LFP side', ...
        'lfpBehaviorRegression: cluster significance threshold.');

    % NGL02_LFP quick-look plot styling (plotTrialparsedTFR_example /
    % plotContinuousTFR). Nested under opt.lfp.plot.*.
    isZlim = @(v) isempty(v) || (isnumeric(v) && numel(v) == 2 && v(1) < v(2));
    isCmap = @(v) ischar(v) || (isnumeric(v) && size(v,2) == 3);
    S(end+1) = optEntry('lfp.plot.visible', 'off', isCh, 'LFP side', ...
        'Figure visibility for the quick-look TFR plots (''on'' | ''off'').');
    S(end+1) = optEntry('lfp.plot.Resolution', 300, isPosIn, 'LFP side', ...
        'exportgraphics DPI for quick-look TFR PNGs.');
    S(end+1) = optEntry('lfp.plot.zlim', [], isZlim, 'LFP side', ...
        'Colour-axis limits [zmin zmax] for quick-look TFRs. [] -> auto.');
    S(end+1) = optEntry('lfp.plot.colormap', 'parula', isCmap, 'LFP side', ...
        'Colormap for quick-look TFRs (name or Nx3 matrix).');
    S(end+1) = optEntry('lfp.plot.trialFilter', 'correct', isCh, 'LFP side', ...
        ['Condition field forming the trial mask for the quick-look TFR ', ...
         '(keeps trials with condition.(field) ~= 0). '''' -> keep all trials.']);
    S(end+1) = optEntry('lfp.plot.baseline', [-0.5 0], isZlim, 'LFP side', ...
        ['dB baseline window [t0 t1] (seconds) for the quick-look TFR. ', ...
         '[] -> raw power, no dB rescale. Default changed 26.06.2026 from [] ', ...
         'to [-0.5 0] (pre-alignment baseline) to match the new opt.toi = [-0.5 4] default.']);
    isInterpMode = @(v) ischar(v) && ismember(lower(v), {'bilinear','nearest','none'});
    S(end+1) = optEntry('lfp.plot.interp', 'bilinear', isInterpMode, 'LFP side', ...
        'imagesc interpolation for quick-look TFR: ''bilinear'' (default, smoother) | ''nearest'' | ''none'' (== nearest).');

    % --- Legacy ---------------------------------------------------------
    S(end+1) = optEntry('neurDyn.do', false, isLog, 'Legacy', ...
        'LEGACY trial-state embedding; superseded by opt.popDyn.trialEmbed.');

    % --- Population dynamics ------------------------------------------
    S(end+1) = optEntry('popDyn.do', false, isLog, 'PopDyn', ...
        'Master gate: run any population-dynamics step.');
    S(end+1) = optEntry('popDyn.pca', true, isLog, 'PopDyn', ...
        'Per-session PCA via calculate_pca_from_pool (single-trial overlay + CI tube).');
    S(end+1) = optEntry('popDyn.jPCA', false, isLog, 'PopDyn', ...
        'Rotational dynamics (PLACEHOLDER).');
    S(end+1) = optEntry('popDyn.GPFA', false, isLog, 'PopDyn', ...
        'Single-trial smooth trajectories (PLACEHOLDER).');
    S(end+1) = optEntry('popDyn.trialEmbed', false, isLog, 'PopDyn', ...
        'Legacy trial-similarity embedding (PCA/tSNE/UMAP per trial).');
    S(end+1) = optEntry('popDyn.smoothSigma', 0.050, isNNNS, 'PopDyn', ...
        'Gaussian smoothing sigma in SECONDS (~50 ms default).');
    S(end+1) = optEntry('popDyn.nComponents', 3, isPosIn, 'PopDyn', ...
        'Output embedding dimensionality.');
    S(end+1) = optEntry('popDyn.conditionVar', '', isCh, 'PopDyn', ...
        'Field name on condition for per-condition grouping (empty = no grouping).');
    S(end+1) = optEntry('popDyn.dropAborted', true, isLog, 'PopDyn', ...
        'Drop aborted trials before grouping (matches legacy FR filter).');
    S(end+1) = optEntry('popDyn.alignIdx', 1, isPosIn, 'PopDyn', ...
        'Index into opt.alignto (ignored by the new PCA path; kept for placeholders).');
    S(end+1) = optEntry('popDyn.trialEmbedMethod', 'tSNE', isTrEmbedMethod, 'PopDyn', ...
        'trialEmbed method: ''PCA''|''tSNE''|''UMAP''.');
    S(end+1) = optEntry('popDyn.pcaConditions', {'allInitiated'}, isNCoC, 'PopDyn', ...
        'Cell of condition tokens (single or ''X vs Y'') iterated by per-session PCA.');

    % --- Waveform extraction ------------------------------------------
    S(end+1) = optEntry('getwF', false, isLog, 'Waveform', ...
        'Extract raw waveforms per cluster (slow).');
    S(end+1) = optEntry('gwfparams.wfWin', [-20 41], isWfWin, 'Waveform', ...
        'Samples around spiketime [pre post] with pre<=0<post.');
    S(end+1) = optEntry('gwfparams.nWf', 2000, isPosIn, 'Waveform', ...
        'Max waveforms per cluster.');
    S(end+1) = optEntry('gwfparams.dataType', 'int16', isCh, 'Waveform', ...
        '.bin sample type (overridden by loadSpikes).');
    S(end+1) = optEntry('gwfparams.nCh', [], isEoP, 'Waveform', ...
        'Set inside loadSpikes from spikes.n_channels_dat.');

    % --- Cluster loading + ISI binning --------------------------------
    S(end+1) = optEntry('spparams.excludeNoise', true, isLog, 'Spike loading', ...
        'Skip Phy ''noise''-labelled clusters.');
    S(end+1) = optEntry('spparams.loadPCs', false, isLog, 'Spike loading', ...
        'Load principal components (rarely needed).');
    S(end+1) = optEntry('isibins', 0:0.5:200, isIsiBins, 'Spike loading', ...
        'ISI histogram bin edges (ms) — strictly increasing vector, >=2 entries.');

    % --- Canonical FR binning -----------------------------------------
    S(end+1) = optEntry('binSize_ms', 200, isPosNS, 'FR binning', ...
        'FR sliding-bin width (ms).');
    S(end+1) = optEntry('stepSz_ms', 20, isPosNS, 'FR binning', ...
        'FR sliding-bin step (ms).');

    % --- Per-area context (set internally) ----------------------------
    S(end+1) = optEntry('area', 'all', isCh1, 'Per-area', ...
        'NGL02 sets this per area; default ''all''.');

    % --- Project-specific gates ---------------------------------------
    S(end+1) = optEntry('proj_chgDtctPCue', false, isLog, 'Project gates', ...
        'Change-Detection P-Cue paradigm (trialdef /32).');
    S(end+1) = optEntry('proj_socialLearning', false, isLog, 'Project gates', ...
        'SocialLearning ASL (TFR testname, etc.).');
    S(end+1) = optEntry('proj_extintion', false, isLog, 'Project gates', ...
        'Extintion paradigm (fireRate_extintion, trialdef -1000 offset).');
    S(end+1) = optEntry('proj_FLIP', false, isLog, 'Project gates', ...
        'vFLIP laminar power analysis.');

    % --- NGL04_fireRate (PSTH plotter) --------------------------------
    S(end+1) = optEntry('fireRatePlot.interval', [-2000 4000], isInt2, 'NGL04_fireRate', ...
        'MS window around alignment passed to plotPSTH.');
    S(end+1) = optEntry('fireRatePlot.binSize_ms', 200, isPosNS, 'NGL04_fireRate', ...
        'FR bin width inside the plot.');
    S(end+1) = optEntry('fireRatePlot.stepSz_ms', 20, isPosNS, 'NGL04_fireRate', ...
        'FR bin step inside the plot (must be <= fireRatePlot.binSize_ms).');
    S(end+1) = optEntry('fireRatePlot.smoothPlot', true, isLog, 'NGL04_fireRate', ...
        'nanMeanSterrHistogram smoothing.');
    S(end+1) = optEntry('fireRatePlot.errAlpha', 0.4, inUnit, 'NGL04_fireRate', ...
        'Error-shade alpha (0..1).');
    S(end+1) = optEntry('fireRatePlot.labelPriority', {'HumanLabel','KSLabel','bc_unitType'}, isNCoC, 'NGL04_fireRate', ...
        'Resolution order for cluster-label tokens.');
    S(end+1) = optEntry('fireRatePlot.busyWarnTraces', 4, isPosNS, 'NGL04_fireRate', ...
        'Warn above N overlaid traces per subplot.');
    S(end+1) = optEntry('fireRatePlot.outDir', '', isCh, 'NGL04_fireRate', ...
        'Empty -> default <input.analysis>/plots/NGL04_fireRate.');
    S(end+1) = optEntry('fireRatePlot.cacheDir', '', isCh, 'NGL04_fireRate', ...
        'Empty -> default <input.analysis>/cache/firepools (shared with NGL04_PCA).');

    % --- NGL04_PCA (state-space plotter) ------------------------------
    S(end+1) = optEntry('pcaPlot.interval', [-2000 4000], isInt2, 'NGL04_PCA', ...
        'MS window around alignment.');
    S(end+1) = optEntry('pcaPlot.binSize_ms', 200, isPosNS, 'NGL04_PCA', ...
        'FR bin width (ms).');
    S(end+1) = optEntry('pcaPlot.stepSz_ms', 20, isPosNS, 'NGL04_PCA', ...
        'FR bin step (ms, must be <= pcaPlot.binSize_ms).');
    S(end+1) = optEntry('pcaPlot.smoothSigma_s', 0.050, isNNNS, 'NGL04_PCA', ...
        'Gaussian sigma for smoothing (s).');
    S(end+1) = optEntry('pcaPlot.nComponents', 3, @(v) isnumeric(v) && isscalar(v) && v >= 2, 'NGL04_PCA', ...
        'Number of PCs to keep (>=2).');
    S(end+1) = optEntry('pcaPlot.nBootstrap', 100, isNNNS, 'NGL04_PCA', ...
        'Trial-bootstrap reps for CI tube; 0 disables.');
    S(end+1) = optEntry('pcaPlot.rngSeed', [], isEoNS, 'NGL04_PCA', ...
        'Integer seed for reproducible CI, or [] for random.');
    S(end+1) = optEntry('pcaPlot.sessionAlpha', 0.18, inUnit, 'NGL04_PCA', ...
        'Alpha for grey single-trial / session-marginal traces.');
    S(end+1) = optEntry('pcaPlot.ciAlpha', 0.20, inUnit, 'NGL04_PCA', ...
        'Alpha for 2D CI ribbon.');
    S(end+1) = optEntry('pcaPlot.ciStride', 10, isPosNS, 'NGL04_PCA', ...
        '3D CI crosshair every N bins.');
    S(end+1) = optEntry('pcaPlot.variants', {'singleTrials','ciTube'}, isVariants, 'NGL04_PCA', ...
        'Which figure variants to render.');
    S(end+1) = optEntry('pcaPlot.outDir', '', isCh, 'NGL04_PCA', ...
        'Empty -> NGL04_PCA defaults to <input.analysis>/plots/PCA; per-session calculate_neural_pca writes to <opt.analysis>/plots/population_dynamics.');

    % --- Gaze / video pipeline (GazEstim via process_gaze) ------------
    % Process_gaze is a wrapper around the GazEstim Python toolbox
    % (toolboxes/GazEstim/{pose_clean,pose_render}.py via configfiles/
    % master_gaze.py). All knobs below are forwarded to the JSON config
    % the wrapper hands to master_gaze.py. Project-default values live
    % here; per-run overrides go in the params struct passed to
    % process_gaze() (typically by NGL06_VideoProcess).
    S(end+1) = optEntry('gaze.do', false, isLog, 'Gaze', ...
        'Master gate: process_gaze runs on each discovered DLC csv.');
    S(end+1) = optEntry('gaze.features', false, isLogOrCh, 'Gaze', ...
        ['Save per-frame derived features to <output>_estimated_features.mat ', ...
         'plus a .png figure. Logical toggle, or an explicit output path.']);
    S(end+1) = optEntry('gaze.video', true, isLog, 'Gaze', ...
        'Render the gaze-overlaid mp4. false -> compute features only (skips rendering; much faster).');
    S(end+1) = optEntry('gaze.fps', 59.94, isPosNS, 'Gaze', ...
        'Input video frame rate (Hz).');
    S(end+1) = optEntry('gaze.downsampleStep', 2, isPosIn, 'Gaze', ...
        'Keep 1 frame per N; out_fps = fps/N.');
    S(end+1) = optEntry('gaze.pCut', 0.5, inUnit, 'Gaze', ...
        'DLC likelihood gate (0..1).');
    S(end+1) = optEntry('gaze.devFac', 0.6, isNNNS, 'Gaze', ...
        'Jump threshold = devFac * bodyLength.');
    S(end+1) = optEntry('gaze.smooth', 5, isPosIn, 'Gaze', ...
        'Temporal smoothing window (frames).');
    S(end+1) = optEntry('gaze.wMed', 9, isPosIn, 'Gaze', ...
        'Rolling-median window (frames).');
    S(end+1) = optEntry('gaze.boneTolFrac', 0.4, isNNNS, 'Gaze', ...
        'Bone-length tolerance fraction.');
    S(end+1) = optEntry('gaze.boneTolMad', 5.0, isNNNS, 'Gaze', ...
        'Bone-length tolerance (xMAD).');
    S(end+1) = optEntry('gaze.orderMargin', 0.10, isNNNS, 'Gaze', ...
        'Head-behind-wing clamp margin (xbody).');
    S(end+1) = optEntry('gaze.videoWidth', 1250, isPosIn, 'Gaze', ...
        'Source video width in pixels (matches DLC training).');
    S(end+1) = optEntry('gaze.videoHeight', 1160, isPosIn, 'Gaze', ...
        'Source video height in pixels.');
    % Body-part selection + role remap. process_gaze reads labels from the
    % csv; opt.gaze.parts picks a subset and opt.gaze.roles.<role> maps a
    % non-standard label onto a pipeline anatomical role. The full role
    % vocabulary is beak/head/back/left_wing/right_wing/tail (all six are
    % registered so applyOverrides keeps any the user sets; '' = identity
    % by name). NOTE: NGL06_videoAnalysis does not forward parts/roles yet.
    S(end+1) = optEntry('gaze.parts', {}, isCoC, 'Gaze', ...
        'Subset of DLC labels to use (cellstr). Empty -> every body part found in the csv.');
    S(end+1) = optEntry('gaze.roles.beak', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the beak (required for gaze cones). Empty -> identity by name.');
    S(end+1) = optEntry('gaze.roles.head', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the head. Empty -> identity by name.');
    S(end+1) = optEntry('gaze.roles.back', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the back. Empty -> identity by name.');
    S(end+1) = optEntry('gaze.roles.left_wing', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the left wing. Empty -> identity by name.');
    S(end+1) = optEntry('gaze.roles.right_wing', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the right wing. Empty -> identity by name.');
    S(end+1) = optEntry('gaze.roles.tail', '', isCh, 'Gaze', ...
        'Role remap: DLC label to treat as the tail. Empty -> identity by name.');
    S(end+1) = optEntry('gaze.drawCones', true, isLog, 'Gaze', ...
        'Render gaze cones on the output video.');
    S(end+1) = optEntry('gaze.monoFOV', 170, isPosNS, 'Gaze', ...
        'Monocular field per eye (degrees).');
    S(end+1) = optEntry('gaze.binoHalf', 15, isNNNS, 'Gaze', ...
        'Binocular half-angle (degrees).');
    S(end+1) = optEntry('gaze.coneMult', 2.5, isPosNS, 'Gaze', ...
        'Cone length = coneMult * birdLength.');
    S(end+1) = optEntry('gaze.eyeFwdFrac', 1/3, isNNNS, 'Gaze', ...
        'Eye base: fraction of head->beak from head.');
    S(end+1) = optEntry('gaze.eyeLatFrac', 1/5, isNNNS, 'Gaze', ...
        'Eye lateral offset: fraction of back->wing.');
    S(end+1) = optEntry('gaze.dpi', 120, isPosIn, 'Gaze', ...
        'Render DPI (encoding).');
    S(end+1) = optEntry('gaze.crf', 24, isPosIn, 'Gaze', ...
        'ffmpeg CRF quality (lower = better, larger files).');
    S(end+1) = optEntry('gaze.preset', 'veryfast', isCh, 'Gaze', ...
        'ffmpeg preset (e.g. ''ultrafast'' / ''veryfast'' / ''medium'').');
    S(end+1) = optEntry('gaze.background', '', isCh, 'Gaze', ...
        'Background image path. Empty -> <analysisCode>/HexArena.png (NGL06 asserts it exists).');
    S(end+1) = optEntry('gaze.masterScript', '', isCh, 'Gaze', ...
        'master_gaze.py path. Empty -> <analysisCode>/master_gaze.py (NGL06 asserts it exists).');
    S(end+1) = optEntry('gaze.pythonExe', '', isCh, 'Gaze', ...
        'Python executable. Empty -> input.GAZEpythonExe (falls back to ''python'' when the machine config doesn''t set it).');
    S(end+1) = optEntry('gaze.previewFrame', [], isEoNS, 'Gaze', ...
        'Render one still PNG at this frame index instead of the full mp4. Empty -> full video.');
    S(end+1) = optEntry('gaze.targetFps', [], isEoP, 'Gaze', ...
        'Alternative to gaze.downsampleStep: pick step so out_fps ~= targetFps. Empty -> use downsampleStep.');
    S(end+1) = optEntry('gaze.startTime', [], isEoNS, 'Gaze', ...
        'Analyse from this time [s]. Empty -> from first frame.');
    S(end+1) = optEntry('gaze.endTime', [], isEoNS, 'Gaze', ...
        'Analyse up to this time [s]. Empty -> to last frame.');
    S(end+1) = optEntry('gaze.maxFrames', [], isEoP, 'Gaze', ...
        'Cap rendered output frames. Empty -> unbounded (subject to gaze.maxSeconds).');
    S(end+1) = optEntry('gaze.maxSeconds', [], isEoP, 'Gaze', ...
        'Cap rendered output duration [s]. Empty -> unbounded (subject to gaze.maxFrames).');
    S(end+1) = optEntry('gaze.overwrite', false, isLog, 'Gaze', ...
        'true -> re-render even if the output file already exists. Default is skip-if-exists.');

    % --- Regen from preprocessed-only (LOCAL-PC PostPhy) --------------
    % Run NGL01 against a data tree where the raw folder is deliberately
    % empty (data moved between machines; raw too big to transfer).
    % chckV is bypassed; recoverInfoForRegen builds info from .system +
    % opt.numChannels. NGL01_Main forces kilosort/bombcell/doNWB off
    % and only re-runs the events/trialdef/conditions chain.
    isRegenSystem = @(v) ischar(v) && ~isempty(v) && ismember(upper(v), {'INTAN','DEUTERON'});
    S(end+1) = optEntry('regenFrom.preproc', false, isLog, 'Regen', ...
        'Master gate. true = skip raw-only steps, rebuild events/trialdef/conditions from existing EventRecord.mat.');
    S(end+1) = optEntry('regenFrom.system', 'INTAN', isRegenSystem, 'Regen', ...
        '''INTAN'' (-> fileperch / 30 kHz) or ''Deuteron'' (-> DF1 / 32 kHz). Only consulted when .preproc=true.');
    S(end+1) = optEntry('regenFrom.fileformat', '', isCh, 'Regen', ...
        'Override fileformat. Empty -> derive from .system.');
    S(end+1) = optEntry('regenFrom.sample_rate', [], isEoP, 'Regen', ...
        'Override amplifier_sample_rate (Hz). Empty -> derive from .system.');
    S(end+1) = optEntry('regenFrom.nChannels', [], isEoP, 'Regen', ...
        'Override channel count. Empty -> use opt.numChannels.');

    % --- Cross-session aggregation (NGL03_acrossSession) --------------
    S(end+1) = optEntry('aggregateSessions', false, isLog, 'Aggregation', ...
        'Build <subject>_aggregated_<area>.mat per (subject, area).');
    S(end+1) = optEntry('aggregateSubjects', false, isLog, 'Aggregation', ...
        'Build study-level aggregated_<area>.mat per area (requires aggregateSessions).');

    % --- Session merge (NGL_mergeSessionsINTAN) -----------------------
    S(end+1) = optEntry('merge.cleanupStaging', false, isLog, 'Merge', ...
        ['NGL_mergeSessionsINTAN: remove the staging folder after a successful ', ...
         'merge. false -> keep it (delete manually). NOTE: the consumer is ', ...
         'currently commented out in NGL_mergeSessionsINTAN.m.']);
end
