function truth = makeFakeStudy(root, varargin)
%MAKEFAKESTUDY  Build the shipped test subject MRX: three sessions, known answers.
%
% PURPOSE:
%   One dataset everyone in the lab tests against. The repository carries this
%   generator rather than the data: a session is tens of megabytes, which does
%   not belong in git, and the generator is seeded, so every machine produces
%   byte-identical files from the same call.
%
% USAGE:
%   makeFakeStudy('D:\TESTSTUDY')
%   makeFakeStudy('D:\TESTSTUDY', 'length', 'full')
%   truth = makeFakeStudy(root, 'sessions', {'19850214'})
%
% INPUTS:
%   root - study folder. The standard tree is created underneath:
%          <root>\data\{raw,preprocessing,trialSorted,spikeSorted,analysis}
%   Name/value pairs:
%     'subject'  default 'MRX'
%     'sessions' default the three shipped dates (see below)
%     'length'   'short' (default, ~8 min per session) or 'full' (~20 min)
%
% THE SESSIONS:
%   Dates are deliberately PRE-1990, in the normal YYYYMMDD format, so a test
%   session can never be confused with a real recording, and each marks
%   something worth remembering:
%     19850214  the first human-to-human email over the Internet in Germany
%     19860704  Rutherford's centenary year of the nucleus is 1911, so this is
%               simply a mid-decade session with a different seed
%     19870321  spring equinox, a third seed
%   Each runs all three task blocks in order: dms, arena, nft.
%
% WHAT IS PLANTED (the whole point):
%   LFP     20 Hz burst after stimOn2 on CORRECT dms trials, NCL only
%           6 Hz theta while walking in arena trials, both areas
%           stimulus-locked response at 1.3 and 2.6 Hz in nft, NCL only
%           a current sink at 325 um on shank 1 after stimOn1
%           one dead channel, one noisy channel, movement artifacts
%   SPIKES  units driven by stimOn1, one by reward, one locked to the tagging
%           stream, one whose amplitude drifts, one labelled noise
%   IMU     a sharp jerk at every peck; slow sway while walking
%   TRIALS  correct / incorrect / omission / aborted, with response latencies
%           that vary per trial between a floor and the response window
%
%   Every session writes fixture_truth.mat next to its data, holding this in
%   machine-readable form, so a test asserts against the design rather than
%   against a previous run.
%
% OUTPUT:
%   truth - struct array, one entry per session.
%
% Last modified 16.09.2026 (Jesus) - new (#F test fixture).

    p = inputParser;
    p.addParameter('subject',  'MRX');
    p.addParameter('sessions', {'19850214', '19860704', '19870321'});
    p.addParameter('length',   'short');
    p.parse(varargin{:});
    a = p.Results;

    assert(~isempty(root) && ischar(root), 'makeFakeStudy:root', ...
        'give a study folder, e.g. makeFakeStudy(''D:\\TESTSTUDY'').');
    for s = a.sessions
        yr = str2double(s{1}(1:4));
        assert(yr < 1990, 'makeFakeStudy:date', ...
            ['fixture sessions must be dated before 1990 so they cannot be ', ...
             'mistaken for real recordings; got %s.'], s{1});
    end

    here = fileparts(mfilename('fullpath'));
    addpath(here);
    truth = struct([]);
    for k = 1:numel(a.sessions)
        t = makeFakeSession(root, a.subject, a.sessions{k}, 'length', a.length);
        if isempty(truth), truth = t; else, truth(k) = t; end
    end

    localWriteReadme(root, a, truth);
    fprintf(['\nmakeFakeStudy: %d session(s) of %s under %s\n' ...
             '  set subjects = {''%s''} and dates = %s in NGL_SetAndRunMe to use them.\n'], ...
            numel(truth), a.subject, root, a.subject, ...
            ['{''' strjoin(a.sessions, ''', ''') '''}']);
end

function localWriteReadme(root, a, truth)
% A plain-text note beside the data, so someone who finds the folder without
% the repository still knows what it is and that it is not a real animal.
    f = fullfile(root, 'FIXTURE_README.txt');
    L = {};
    L{end+1} = 'SYNTHETIC TEST DATA - NOT A REAL ANIMAL, NOT REAL RECORDINGS.';
    L{end+1} = '';
    L{end+1} = sprintf('Subject %s, sessions %s, generated by tests/fixture/makeFakeStudy.m', ...
                       a.subject, strjoin(a.sessions, ', '));
    L{end+1} = 'Dates are pre-1990 so these can never be confused with real sessions.';
    L{end+1} = '';
    L{end+1} = 'Every effect in this data was planted deliberately. What each';
    L{end+1} = 'analysis should find is written in fixture_truth.mat, next to each';
    L{end+1} = 'session''s preprocessing folder. Regenerate with:';
    L{end+1} = sprintf('    makeFakeStudy(''%s'', ''length'', ''%s'')', root, a.length);
    L{end+1} = '';
    for k = 1:numel(truth)
        L{end+1} = sprintf('%s: %.0f s, %d trials, seed %d', truth(k).session, ...
                           truth(k).duration, truth(k).nTrials, truth(k).seed); %#ok<AGROW>
        for b = truth(k).blocks(:)'
            L{end+1} = sprintf('   BLOCK- %-5s %6.1f - %6.1f s, %d trials', ...
                b.task, b.tStart, b.tEnd, numel(b.trials)); %#ok<AGROW>
        end
        for n = truth(k).lfp.notes(:)'
            L{end+1} = ['   LFP  - ' n{1}]; %#ok<AGROW>
        end
        for n = truth(k).spikes.notes(:)'
            L{end+1} = ['   SPK  - ' n{1}]; %#ok<AGROW>
        end
        for n = truth(k).imu.notes(:)'
            L{end+1} = ['   IMU  - ' n{1}]; %#ok<AGROW>
        end
    end
    fid = fopen(f, 'w');
    fprintf(fid, '%s\n', L{:});
    fclose(fid);
end
